routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\Orders\Http\Controllers\CartAccountController;
use Bittacora\Bpanel4\Orders\Http\Controllers\CartController;
use Bittacora\Bpanel4\Orders\Http\Controllers\CartShippingController;
use Bittacora\Bpanel4\Orders\Http\Controllers\MyOrdersController;
use Bittacora\Bpanel4\Orders\Http\Controllers\OrderAdminController;
use Bittacora\Bpanel4\Orders\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;

Route::prefix('/carrito')->name('cart.')->middleware(['web'])->group(function () {
    Route::get('/', [CartController::class, 'show'])->name('show');
    Route::get('/seleccionar-envio', [CartShippingController::class, 'show'])->name('select-shipping');
    Route::post('/vista-previa', [CartController::class, 'preview'])->name('preview');
    Route::get('{cartRow}/quitar', [CartController::class, 'removeProduct'])->name('remove-product');
    Route::get('/crear-cuenta', [CartAccountController::class, 'showRegistration'])->name('show-registration');
    Route::post('/crear-cuenta', [CartAccountController::class, 'register'])->name('register');
});

Route::prefix('/pedido')->name('order.')->middleware(['web'])->group(function () {
    Route::get('/confirmar', [OrderController::class, 'confirm'])->name('confirm');
    Route::get('/pedido-confirmado', [OrderController::class, 'confirmed'])->name('confirmed');
    Route::get('/cancelado', [OrderController::class, 'cancelled'])->name('cancelled');
});

Route::prefix('bpanel/pedidos')->name('orders-admin.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(static function () {
        Route::get('/listar', [OrderAdminController::class, 'index'])->name('index');
        Route::get('{order}/editar', [OrderAdminController::class, 'edit'])->name('edit');
        Route::put('{order}/actualizar', [OrderAdminController::class, 'update'])->name('update');
        Route::put('{order}/cambiar-estado', [OrderAdminController::class, 'updateStatus'])->name('updateStatus');
        Route::delete('{order}/eliminar', [OrderAdminController::class, 'destroy'])->name('destroy');
        Route::get('/comprobar-num-factura/{order}/{invoiceNumber}', [OrderAdminController::class, 'checkInvoiceNumber'])->name('checkInvoiceNumber');
    });

Route::post('/create-cart', [CartController::class, 'create']); // Se usa principalmente en los tests

Route::prefix('mi-cuenta')->name('my-account.')->middleware(['web'])->group(static function () {
    Route::get('/mis-pedidos', [MyOrdersController::class, 'index'])->name('orders');
    Route::get('/ver-pedido/{order}', [MyOrdersController::class, 'show'])->name('view-order');
});

resources/views/bpanel/livewire/datatable-columns/actions.blade.php
@livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'orders-admin', 'model' =>
$row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el pedido?'],
key('order-buttons-'.$row->id))

resources/views/bpanel/livewire/datatable-columns/invoice-number.blade.php
@php use Bittacora\Bpanel4\Invoices\Models\Invoice; @endphp
@if(!Invoice::where('order_id', $row->getId())->whereNotNull('invoice_number')->exists())
    -
@else
    {{ Invoice::where('order_id', $row->getId())->whereNotNull('invoice_number')->firstOrFail()->getInvoiceNumber()}}
@endif

resources/views/bpanel/livewire/datatable-columns/invoice.blade.php
@if(!\Bittacora\Bpanel4\Invoices\Models\Invoice::where('order_id', $row->getId())->whereNotNull('invoice_path')->exists())
    <a href="{{ URL::signedRoute('bpanel4-invoices.get-invoice', ['order' => $row->getId()]) }}"
       title="Generar factura">
        <i class="far fa-plus"></i>
    </a>
@else
    <a href="{{ URL::signedRoute('bpanel4-invoices.get-invoice', ['order' => $row->getId()]) }}"
       title="Descargar factura">
        <i class="far fa-file-invoice-dollar"></i>
    </a>
@endif

resources/views/bpanel/livewire/datatable-columns/order-status.blade.php
<div class="order-list-status">
    <div style="color: {{ $row->getStatus()->color }};background: {{ $row->getStatus()->background_color }}">{{ $row->getStatus()->name }}</div>
</div>

resources/views/bpanel/livewire/order-product-editor.blade.php
<div class="order-product-editor">
    <div class="title">Editar producto "{!! strip_tags($orderProduct->getName()) !!}"</div>
    <div class="fields">
        <div class="name">
            <label for="order-product-{{ $orderProduct->getId() }}-name">Nombre:</label>
            <input wire:model="name" id="order-product-{{ $orderProduct->getId() }}-name" maxlength="250" class="form-control">
        </div>
        <div class="reference">
            <label for="order-product-{{ $orderProduct->getId() }}-reference">Referencia:</label>
            <input wire:model="reference" id="order-product-{{ $orderProduct->getId() }}-reference" maxlength="250" class="form-control">
        </div>
        <div class="quantity">
            <label for="order-product-{{ $orderProduct->getId() }}-quantity">Cantidad:</label>
            <input wire:model="quantity"
                   type="number"
                   min="1"
                   step="1"
                   id="order-product-{{ $orderProduct->getId() }}-quantity"
                   class="form-control"
            >
        </div>
        <div class="unit-price">
            <label for="order-product-{{ $orderProduct->getId() }}-price">Precio unitario (sin impuestos):</label>
            <input wire:model="paidUnitPrice"
                   id="order-product-{{ $orderProduct->getId() }}-price"
                   type="number"
                   min="0"
                   step="0.01"
                   class="form-control"
            >
        </div>
        <div class="vat-rate">
            <label for="order-product-{{ $orderProduct->getId() }}-vat-rate">Tipo de IVA:</label>
            <select wire:model="vatRate" id="order-product-{{ $orderProduct->getId() }}-vat-rate" class="form-control">
                @foreach(\Bittacora\Bpanel4\Vat\Models\VatRate::whereActive(true)->get()->all() as $vatRate)
                   <option value="{{ $vatRate->getRate() }}">{{ $vatRate->getRate() }} %</option>
                @endforeach
            </select>
        </div>
        <div class="total">
            <label>Total (sin impuestos):</label>
            <input readonly wire:model="total" class="form-control">
        </div>
        <div class="total-with-taxes">
            <label>Total (con impuestos):</label>
            <input readonly wire:model="totalWithTaxes" class="form-control">
        </div>
    </div>
    <div class="text-right">
        <button class="btn btn-secondary" wire:click="cancel"><i class="fas fa-times"></i> Cancelar</button>
        <button class="btn btn-primary ml-3" wire:click="updateProduct"><i class="fas fa-save"></i> Guardar</button>
    </div>

</div>

resources/views/bpanel/livewire/orders-datatable.blade.php
<?php /** @var \Bittacora\Bpanel4\Orders\Models\Order\Order $row */ ?>
<td>{{ $row->getClient()->getName() }}</td>
<td>{{ $row->getClient()->getSurname() }}</td>
<td class="text-center order-number">{{ $row->getId() }}</td>
<td class="text-center order-total">{{ \Bittacora\Bpanel4\Prices\Types\Price::fromInt($row->getOrderTotal()) }}</td>
<td class="text-center order-date">{{ $row->getDate()->format('d-m-Y H:i:s') }}</td>
<td class="order-list-status"><div style="color: {{ $row->getStatus()->color }};background: {{ $row->getStatus()->background_color }}">{{ $row->getStatus()->name }}</div></td>
<td class="text-center">
    @if(!\Bittacora\Bpanel4\Invoices\Models\Invoice::where('order_id', $row->getId())->whereNotNull('invoice_path')->exists())
        <a href="{{ URL::signedRoute('bpanel4-invoices.get-invoice', ['order' => $row->getId()]) }}"
           title="Generar factura">
            <i class="far fa-plus"></i>
        </a>
    @else
        <a href="{{ URL::signedRoute('bpanel4-invoices.get-invoice', ['order' => $row->getId()]) }}"
           title="Descargar factura">
            <i class="far fa-file-invoice-dollar"></i>
        </a>
    @endif
</td>
<td class="text-center">
    @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'orders-admin', 'model' =>
    $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el pedido?'],
    key('order-buttons-'.$row->id))
</td>

resources/views/bpanel/livewire/partials/create-order-product.blade.php
<div>
    <div class="order-product-editor">
        <div class="title">Añadir producto</div>
        <div class="fields">
            <div class="name">
                <label for="order-product-name">Nombre:</label>
                <input wire:model="name" id="order-product-name" maxlength="250" class="form-control">
            </div>
            <div class="reference">
                <label for="order-product-reference">Referencia:</label>
                <input wire:model="reference" id="order-product-reference" maxlength="250" class="form-control">
            </div>
            <div class="quantity">
                <label for="order-product-quantity">Cantidad:</label>
                <input wire:model="quantity"
                       type="number"
                       min="1"
                       step="1"
                       id="order-product-quantity"
                       class="form-control"
                >
            </div>
            <div class="unit-price">
                <label for="order-product-price">Precio unitario (sin impuestos):</label>
                <input wire:model="unitPrice"
                       id="order-product-price"
                       type="number"
                       min="0"
                       step="0.01"
                       class="form-control"
                >
            </div>
            <div class="vat-rate">
                <label for="order-product-vat-rate">Tipo de IVA:</label>
                <select wire:model="taxRate" id="order-product-vat-rate" class="form-control">
                    @foreach(\Bittacora\Bpanel4\Vat\Models\VatRate::whereActive(true)->get()->all() as $vatRate)
                        <option value="{{ $vatRate->getRate() }}">{{ $vatRate->getRate() }} %</option>
                    @endforeach
                </select>
            </div>
            <div class="total">
                <label>Total (sin impuestos):</label>
                <input readonly wire:model="total" class="form-control">
            </div>
            <div class="total-with-taxes">
                <label>Total (con impuestos):</label>
                <input readonly wire:model="totalWithTaxes" class="form-control">
            </div>
        </div>
        <div class="text-right">
            <button class="btn btn-secondary" wire:click="cancel"><i class="fas fa-times"></i> Cancelar</button>
            <button class="btn btn-primary ml-3" wire:click="createProduct"><i class="fas fa-save"></i> Guardar</button>
        </div>
    </div>
</div>

resources/views/bpanel/livewire/partials/order-product-editor.blade.php
<tr>
    <td colspan="5" class="order-product-editor">
        @livewire('bpanel4-orders::order-product-editor', ['orderProduct' => $product], key('order-product-editor-' . $product->getId()))
    </td>
</tr>

resources/views/bpanel/livewire/partials/order-product-row.blade.php
<tr class="order-product-row">
    <td>
        @if(null !== $product->getProductId())
            <a href="{{ route('bpanel4-products.edit', ['model' => $product->getProductId()]) }}"
               class="d-flex"
               style="gap: 1rem">
                {!! $product->getName() !!}
            </a>
        @else
            <div class="product-name d-flex" style="gap: 1rem;">
                {!! $product->getName() !!}
            </div>
        @endif
        <div><small><em>Ref.: {{ $product->getReference() }}</em></small></div>
        <livewire:bpanel4-orders::livewire.order-product-meta-editor :orderProduct="$product"
                                                                     :enableEdit="$orderCanBeEdited"
                                                                     wire:key="order-product-meta-{{ $product->getId() }}"/>
    </td>
    <td class="text-right">{{ $product->getQuantity() }}</td>
    <td class="text-right">{{ $product->getPaidUnitPrice() }}</td>
    <td class="text-right">{{ $product->getTotal() }}</td>
    <td class="text-right">
        @if($orderCanBeEdited)
            <button class="btn btn-link" wire:click="editProduct({{ $product->getId() }})">
                <i class="far fa-pencil text-info mr-2" title="Editar producto"></i></button>
            <button class="btn btn-link"
                    wire:click="removeProduct({{ $product->getId() }})"
                    onclick="confirm('¿Confirma que desea eliminar el producto del pedido?') || event.stopImmediatePropagation()">
                <i class="far fa-trash-alt text-danger" title="Eliminar producto"></i>
            </button>
        @endif
    </td>
</tr>

resources/views/bpanel/order/edit.blade.php
<?php /** @var \Bittacora\Bpanel4\Orders\Models\Order\Order $order */ ?>
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Edición de pedido: ' . $order->getId())

@section('content')
    <style>
        span.product-attribute-in-name {
            color: #6b6b6b;
        }
    </style>
    <div class="card bcard mb-5">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-orders::form.edit') }}</span>
            </h4>
        </div>
        <div class="p-3">
            <form action="{{ route('orders-admin.updateStatus', ['order' => $order]) }}" method="post">
                @method('put')
                @csrf
                @livewire('form::select', ['name' => 'order_status', 'labelText' =>
                __('bpanel4-orders::form.order_status'),
                'fieldWidth' => 7, 'required'=>true, 'allValues' => $orderStatus, 'selectedValues' =>
                [$order->order_status_id], 'helpText' => 'Si marca el pedido como "En espera", podrá modificarlo. Tenga en cuenta que al marcar el pedido como completado, se volverá a enviar la factura al cliente, con los datos actualizados.'])
                <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                    @livewire('form::save-button',['theme'=>'update'])
                    @livewire('form::save-button',['theme'=>'reset'])
                </div>
            </form>
        </div>
    </div>
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-orders::form.details') }}</span>
            </h4>
        </div>
        @livewire('bpanel4-orders::order-editor', [
            'order' => $order,
            'orderCanBeEdited' => $orderCanBeEdited,
            'invoiceNumber' => $invoiceNumber,
            'orderStatus' => $orderStatus,
            'invoice' => $invoice,
        ], key('order-editor-'. $order->getId()))
    </div>
@push('scripts')
    <script>
        /* Mostrar un aviso si el número de factura ya está en uso en otro pedido */
        const invoiceField = document.getElementById('invoiceNumber');

        if (null !== document.getElementById('invoiceNumber')) {
          invoiceField.addEventListener('keyup', function () {
            const invoiceNumber = invoiceField.value;
            const invoiceNumberStatus = document.getElementById('invoiceNumberStatus');
            let baseUrl = '{{ route('orders-admin.checkInvoiceNumber', [
            'order' => $order,
            'invoiceNumber' => ':invoiceNumber:'
          ]) }}';
            baseUrl = baseUrl.replace(':invoiceNumber:', invoiceNumber);
            fetch(baseUrl).then(function (response) {
              return response.json();
            }).then(function (response) {
              if (true === response) {
                // El número de factura ya está en uso
                invoiceNumberStatus.style.display = 'flex';
                return;
              }
              invoiceNumberStatus.style.display = 'none';
            }).catch(function (err) {
            });
          });
        }
    </script>
@endpush
@endsection

resources/views/bpanel/order/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Pedidos')

@section('content')

    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-orders::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('bpanel4-orders::livewire.orders-table', [], key('bpanel4-orders-datatable'))
        </div>
    </div>


@endsection

resources/views/cart/cart-addresses.blade.php
@extends('bpanel4-public.layouts.regular-page')

@section('content')
    <div class="regular-page-container">
        <form method="POST" action="{{ route('cart.preview') }}">
            @csrf
            @livewire('bpanel4-orders::cart-addresses', ['client' => $client])
            @livewire('bpanel4-orders::select-shipping', ['client' => $client, 'cart' => $cart])
        </form>
    </div>
@endsection

resources/views/cart/cart.blade.php
@extends('bpanel4-public.layouts.regular-page')

@section('meta-title') {{ __('Carrito') }} @endsection
@section('meta-description'){{ __('Carrito de :name', ['name' => config('app.name')]) }}@endsection
@section('meta-keywords'){{ __('carrito') }}@endsection

@section('content')
    <div class="regular-page-container bootstrap">
        @livewire('bpanel4-orders::cart')
    </div>
@endsection

resources/views/cart/mini-cart.blade.php
<div>
    <a href="{{ route('cart.show') }}" title="Ir al carrito">
        <div class="cart-icon">
            <i class="far fa-shopping-cart"></i>
            <div class="quantity">
                {{ $productCount }}
            </div>
        </div>
    </a>
    <script>
      window.addEventListener('cart-updated', event => {
        toastr.success('Carrito actualizado');
      })
    </script>
</div>

resources/views/cart/preview.blade.php
@extends('bpanel4-public.layouts.regular-page')

@section('content')
    <div class="regular-page-container">
        <div class="regular-page-container">
            @livewire('bpanel4-orders::cart', [
                'shippingOption' => $shippingOption,
                'shippingAddress' => $shippingAddress,
                'billingAddress' => $billingAddress,
                'isPreview' => true
            ])
        </div>
    </div>
@endsection

resources/views/cart/register-form.blade.php
<?php /** @var \Bittacora\Bpanel4\Clients\Models\Client $client */ ?>
@extends('bpanel4-public.layouts.regular-page')
@livewireStyles
@section('content')
    <div class="main-container regular-page-container bgc-transparent">
        <div class="main-content minh-100 justify-content-center">
            <p>Para continuar con su pedido, necesitamos los siguientes datos. Por favor, rellene el formulario y haga click en continuar.</p>
            @if($errors->any())
                {!! implode('', $errors->all('<div>:message</div>')) !!}
            @endif
            <form method="POST" action="{{ route('cart.register') }}" class="registration-form cart-registration-form">
                @csrf

                <fieldset class="d-flex flex-wrap mt-3 pb-4 w-100">
                    <legend><i class="fa-fw fas fa-user"></i> <strong>Datos personales</strong></legend>
                    <div class="d-flex w-100">
                        <div class="col-md-6 pb-4 px-0 pr-4">
                            @livewire('form::input-text', ['fieldWidth' => 9, 'name' => 'name', 'labelText' =>
                            __('bpanel4-clients::client.name'),
                            'required'=>true, 'value' => old('name')])
                        </div>
                        <div class="col-md-6 pb-4 px-0">
                            @livewire('form::input-text', ['fieldWidth' => 9, 'name' => 'surname', 'labelText' =>
                            __('bpanel4-clients::client.surname'), 'required'=>true, old('surname')])
                        </div>
                    </div>
                    <div class="d-flex w-100">
                        <div class="col-md-6 pb-4 px-0 pr-4">
                            @livewire('form::input-text', ['fieldWidth' => 9, 'name' => 'dni', 'labelText' =>
                            __('bpanel4-clients::client.dni'),
                            'required'=>true, old('dni')])
                        </div>
                        <div class="col-md-6 pb-4 px-0">
                            @livewire('form::input-text', ['fieldWidth' => 9, 'name' => 'company', 'labelText' =>
                            __('bpanel4-clients::client.company-name-label'), 'required'=>false, old('company')])
                        </div>
                    </div>
                    <div class="d-flex w-100">
                        <div class="col-md-6 pb-4 px-0 pr-4">
                            @livewire('form::input-email', ['fieldWidth' => 9, 'name' => 'email', 'labelText' =>
                            __('bpanel4-clients::client.email'), 'required'=>true, old('email')])
                        </div>
                        <div class="col-md-6 pb-4 px-0">
                            @livewire('form::input-text', ['fieldWidth' => 9, 'name' => 'phone', 'labelText' =>
                            __('bpanel4-clients::client.phone'), 'required'=>true, old('phone')])
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend><i class="fa-fw fas fa-location-circle"></i> <strong>Dirección</strong></legend>
                    <div class="d-flex w-100">
                        <div class="col-md-12 pb-4 px-0 address-name">
                            @livewire('form::input-text', ['labelWidth' => 5, 'fieldWidth' => 7 , 'name' =>
                            'address[name]', 'labelText' =>
                            __('bpanel4-addresses::address.name'), 'required'=>true, 'value' => old('address.name'),
                            'placeholder' => __('bpanel4-addresses::address.name-placeholder')])
                        </div>
                    </div>
                    <div class="d-flex w-100">
                    {{-- Nombre de la persona de contacto --}}
                    <div class="col-md-6 pb-4 px-0 pr-4">
                        @livewire('form::input-text', [
                        'fieldWidth' => 9 ,
                        'name' =>  'address[person_name]',
                        'labelText' => __('bpanel4-addresses::address.person_name'),
                        'required'=>true,
                        'value' => old('person_name'),
                        'placeholder' => __('bpanel4-addresses::address.person_name_placeholder')
                        ], key('person_name-'. Str::random(10)))
                    </div>
                    {{-- Apellidos de la persona de contacto --}}
                    <div class="col-md-6 pb-4 px-0">
                        @livewire('form::input-text', [
                        'fieldWidth' => 9 ,
                        'name' => 'address[person_surname]',
                        'labelText' => __('bpanel4-addresses::address.person_surname'),
                        'required'=>true,
                        'value' => old('person_surname'),
                        'placeholder' => __('bpanel4-addresses::address.person_surname_placeholder')
                        ], key('person_surname-'. Str::random(10)))
                    </div>
                    </div>
                    <div class="d-flex w-100">
                        <div class="col-md-6 pb-4 px-0 pr-4 d-flex w-100 align-items-center country-field">
                            <div class="col-sm-2 col-form-label text-sm-right">
                                <label for="id-form-field-1" class="mb-0  ">
                                    <span class="text-danger">*</span> País
                                </label>
                            </div>
                            <div class="col-sm-10">
                                <div class="input-group m-b">
                                    @livewire('country-select', ['selectedCountry' => old('country') ?? config('bpanel4-clients.default_country_id', 0), 'required' => true])
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 pb-4 px-0 d-flex form-group align-items-center">
                            <div class="col-sm-3 col-form-label text-sm-right">
                                <label for="id-form-field-1" class="mb-0  ">
                                    <span class="text-danger">*</span> Provincia
                                </label>
                            </div>
                            <div class="col-sm-9 ">
                                <div class="input-group m-b">
                                    @livewire('state-select', ['selectedCountry' => old('country') ?? config('bpanel4-clients.default_country_id', 0), 'selectedState' => old('state') ?? 0, 'required' => true])
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex w-100">
                        <div class="col-md-6 pb-4 px-0 pr-4 ">
                            @livewire('form::input-text', ['labelWidth' => 3, 'fieldWidth' => 9, 'name' => 'address[location]', 'labelText' =>
                            __('bpanel4-addresses::address.location'), 'required'=>true, 'value' => old('address.location')])
                        </div>
                        <div class="col-md-6 pb-4 pl-3 pr-0">
                            @livewire('form::input-text', ['labelWidth' => 4, 'fieldWidth' => 8, 'name' => 'address[postal_code]', 'labelText' =>
                            __('bpanel4-addresses::address.postal-code'), 'required'=>true, 'value' => old('address.postal_code')])
                        </div>
                    </div>
                    <div class="d-flex w-100 address-address">
                        <div class="col-md-12 pb-4 px-0">
                            @livewire('form::input-text', ['labelWidth' => 2, 'fieldWidth' => 10, 'name' => 'address[address]', 'labelText' =>
                            __('bpanel4-addresses::address.address'), 'required'=>true, 'value' =>
                            old('address.address') ])
                        </div>
                    </div>
                </fieldset>
                @livewire('form::input-hidden', ['name' => 'password', 'value' => $password])
                @livewire('form::input-hidden', ['name' => 'password_confirmation', 'value' => $password])

                <div class="registration-legal-checkbox">
                    @livewire('form::input-checkbox', [
                    'name' => 'accept-policies',
                    'value' => 1,
                    'checked' => false,
                    'labelText' => __('bpanel4-clients::my-account.accept-privacy-policy', [
                    'privacy-policy-link' => config('bpanel4-clients.privacy-policy-page'),
                    'basic-data-protection-link' => config('bpanel4-clients.basic-data-protection-link')
                    ]),
                    'required' => true,
                    'bpanelForm' => true]
                    )
                    @include(config('bpanel4-clients.data-protection-view'))
                </div>
                @if(config('captcha.secret'))
                    <div class="mt-3 d-flex align-items-end flex-column">
                        {!! NoCaptcha::renderJs() !!}
                        {!! NoCaptcha::display() !!}
                        @if ($errors->has('g-recaptcha-response'))
                            <div class="text-danger mt-3">
                                <strong>{{ __('El captcha es obligatorio') }}</strong>
                            </div>
                        @endif
                    </div>
                @endif
                <input type="hidden" name="client_type" value="particular" id="client_type">
                <div></div>
                <div class="d-flex justify-content-end mt-4">
                    <button class="btn btn-primary">
                        {{ __('bpanel4-clients::client.continue'), }}
                    </button>
                </div>
            </form>

        </div>
        <script defer>
          // Autocompleto nombre de la dirección con el del cliente por comodidad, pero permito que sean distintos
          const nameField = document.getElementById('name');
          const surnameField = document.getElementById('surname');
          const personNameField = document.querySelector('[name="address\[person_name\]"]');
          const personSurameField = document.querySelector('[name="address\[person_surname\]"]');

          function bindFields(mainField, secondaryField) {
            mainField.addEventListener('change', function () {
              secondaryField.value = mainField.value;
            });
          }

          bindFields(nameField, personNameField);
          bindFields(surnameField, personSurameField);
        </script>
    </div>
@endsection

resources/views/livewire/cart-error.blade.php
<div>
    @php
        $messages = [];

        if ($isShippingAddressError) {
           $messages[] = 'de envío';
        }

        if ($isBillingAddressError) {
           $messages[] = 'de facturación';
        }

        $message = implode(' y ', $messages);
    @endphp
    <div class="alert alert-danger mt-5">
        @if ($cartError === 'address-error')
            Su dirección {{ $message }} está incompleta o es incorrecta, por favor, diríjase al apartado <a href="{{ route('my-account.edit-address', ['address' => $cartErrorAddress]) }}">"Mis direcciones"</a> y corríjala.
        @endif
    </div>
</div>

resources/views/livewire/datatable-columns/actions.blade.php
<a href="{{ route('my-account.view-order', ['order' => $row->getId()]) }}"><i class="far fa-eye"></i> Ver</a>

resources/views/livewire/datatable-columns/invoice.blade.php
<div>
    <x-invoice-download-button :order="$row"/>
</div>

resources/views/order/confirmed.blade.php
@extends('bpanel4-public.layouts.regular-page')

@section('content')
    <div class="regular-page-container">
        <div class="d-flex flex-column justify-content-center align-items-center" style="min-height: 600px;">
            <h1 class="mb-5">{{ __('¡Pedido confirmado!') }}</h1>
            <p>{{ __('¡Gracias por su pedido! Revise su dirección de correo electrónico para ver los detalles de su pedido.') }}</p>
            @if(!$isGuest)
                <p class="mb-5">{{ __('También podrá verlos desde el apartado') }} <strong><a href="{{ route('my-account.index') }}">{{ __('Mis pedidos') }}</a></strong>,
                   {{ __('dentro de') }} <strong><a href="{{ route('my-account.index') }}">{{ __('Mi cuenta') }}</a></strong>.</p>
            @endif
            <a href="{{ route('home') }}"><button class="btn btn-primary">{{ __('Volver a la página de inicio') }}</button></a>
        </div>
    </div>
@endsection